### ISSUE TITLE
Unable to download confluence-source from PyPi

### ISSUE THREAD

**Issue by arekball** [airbytehq/PyAirbyte#345]
Using airbyte==0.12.0 with Python 3.9.15, my confluence source stopped working with `airbyte.exceptions.AirbyteConnectorNotPyPiPublishedError: AirbyteConnectorNotPyPiPublishedError: Connector found, but not published to PyPI.`.

I believe the [registry](https://connectors.airbyte.com/files/registries/v0/oss_registry.json) changed but I was wondering what the reason for this change is. I suspect it may be related to #340 since confluence is manifest-only in the newer versions of PyAirbyte, but is there a way to get it working on 0.12.0? I already tried downloading from pypi manually, but it seems that the airbyte-cdk requirements for the newest `airbyte-source-confluence` are `airbyte-cdk==0.80.0`, but my airbyte requires `airbyte-cdk<2.0.0,>=1.2.1`, which pip cant resolve.

I know this package is in beta, but also wanted to ask what the strategy is going forward and what we can expect in regards to maintenance of older versions.

**Comment by aaronsteers** [comment]
@arekball - Thanks very much for reporting this issue.

We have a pending fix in #347.

As you correctly determined, the root cause is a migration to yaml-based manifests. As a workaround, you may be able to provide an explicit `pip_url` (`airbyte-source-confluence`) and optional `version` argument in `get_source()`, which _should_ locate an explicit version of the connector from PyPi, regardless of the registry declaration.

In this case, PyAirbyte should install the connector in a separate virtualenv, which in theory should prevent the version conflict issue you mention.

Another potential workaround would be to specific `source_manifest=True` in `get_source()`, which would tell PyAirbyte to similarly ignore the registry, and prefer a yaml manifest.


Hope this helps! You'll also see an update here once #347 ships.

**Comment by aaronsteers** [comment]
@arekball - #347 is now merged and released in https://github.com/airbytehq/PyAirbyte/releases/tag/v0.17.1.

Can you confirm if this resolves your issue?
